version: "3.8"
services:
  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "25:25"
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
    restart: unless-stopped